"""initial schema

Revision ID: 77b7230f50b1
Revises: 
Create Date: 2026-09-11 18:56:31.769054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b7230f50b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaches_canonical_key'), 'coaches', ['canonical_key'], unique=True)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_code'), 'competitions', ['code'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_canonical_key'), 'players', ['canonical_key'], unique=True)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('referees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referees_canonical_key'), 'referees', ['canonical_key'], unique=True)
    op.create_index(op.f('ix_referees_name'), 'referees', ['name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('A_UNRESTRICTED', 'B_PERSONAL_USE_ONLY', 'C_ABSTRACT_ONLY', name='datasourcecategory'), nullable=False),
    sa.Column('is_implemented', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_key'), 'sources', ['key'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_canonical_key'), 'teams', ['canonical_key'], unique=True)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injuries_player_id'), 'injuries', ['player_id'], unique=False)
    op.create_index(op.f('ix_injuries_team_id'), 'injuries', ['team_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family', sa.Enum('DIXON_COLES_POISSON', 'NEGATIVE_BINOMIAL', 'LOGISTIC_REGRESSION', 'GRADIENT_BOOSTING', 'BAYESIAN_HIERARCHICAL', 'PLAYER_PROP_MODEL', 'ENSEMBLE', name='modelfamily'), nullable=False),
    sa.Column('market_category', sa.String(length=64), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_data_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hyperparameters_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_competition_id'), 'model_versions', ['competition_id'], unique=False)
    op.create_table('referee_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('matches_officiated', sa.Integer(), nullable=False),
    sa.Column('avg_fouls_per_match', sa.Float(), nullable=True),
    sa.Column('avg_yellow_cards_per_match', sa.Float(), nullable=True),
    sa.Column('avg_red_cards_per_match', sa.Float(), nullable=True),
    sa.Column('penalties_awarded_rate', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referee_stats_as_of_date'), 'referee_stats', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_referee_stats_referee_id'), 'referee_stats', ['referee_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'label', name='uq_season_competition_label')
    )
    op.create_index(op.f('ix_seasons_competition_id'), 'seasons', ['competition_id'], unique=False)
    op.create_table('tactical_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('window_matches', sa.Integer(), nullable=False),
    sa.Column('opponent_adjusted', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tactical_features_as_of_date'), 'tactical_features', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_tactical_features_feature_name'), 'tactical_features', ['feature_name'], unique=False)
    op.create_index(op.f('ix_tactical_features_player_id'), 'tactical_features', ['player_id'], unique=False)
    op.create_index(op.f('ix_tactical_features_team_id'), 'tactical_features', ['team_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('to_team_id', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('fee_eur', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_player_id'), 'transfers', ['player_id'], unique=False)
    op.create_index(op.f('ix_transfers_to_team_id'), 'transfers', ['to_team_id'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_predictions', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('yield_pct', sa.Float(), nullable=True),
    sa.Column('profit_units', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('leakage_check_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_model_version_id'), 'backtests', ['model_version_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=True),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LINEUPS_OUT', 'IN_PLAY', 'FINISHED', 'POSTPONED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('home_goals_ft', sa.Integer(), nullable=True),
    sa.Column('away_goals_ft', sa.Integer(), nullable=True),
    sa.Column('home_goals_ht', sa.Integer(), nullable=True),
    sa.Column('away_goals_ht', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_external_ref'), 'matches', ['external_ref'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_kickoff_utc'), 'matches', ['kickoff_utc'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_table('analysis_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('data_snapshot_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_versions_is_current'), 'analysis_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_analysis_versions_match_id'), 'analysis_versions', ['match_id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=16), nullable=True),
    sa.Column('is_starting', sa.Boolean(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Enum('OFFICIAL', 'PROBABLE_CONFIRMED', 'PROBABLE_CONFLICTING', 'UNKNOWN', name='lineupconfidence'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineups_match_id'), 'lineups', ['match_id'], unique=False)
    op.create_index(op.f('ix_lineups_player_id'), 'lineups', ['player_id'], unique=False)
    op.create_index(op.f('ix_lineups_team_id'), 'lineups', ['team_id'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('MATCH_RESULT', 'DOUBLE_CHANCE', 'HANDICAP', 'TOTAL_GOALS', 'BOTH_TEAMS_TO_SCORE', 'CORNERS', 'CARDS', 'FOULS', 'PLAYER_SHOTS', 'PLAYER_SHOTS_ON_TARGET', 'PLAYER_GOALS', 'PLAYER_ASSISTS', 'PLAYER_CARDS', 'PLAYER_FOULS', 'PLAYER_PASSES', name='marketcategory'), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_category'), 'markets', ['category'], unique=False)
    op.create_index(op.f('ix_markets_match_id'), 'markets', ['match_id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('key_passes', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('fouls_suffered', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_stats_match_id'), 'player_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_stats_team_id'), 'player_stats', ['team_id'], unique=False)
    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('fouls_committed', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('possession_pct', sa.Float(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xga', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_stats_match_id'), 'team_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_team_stats_team_id'), 'team_stats', ['team_id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('forecast_at', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_match_id'), 'weather', ['match_id'], unique=True)
    op.create_table('market_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_outcomes_market_id'), 'market_outcomes', ['market_id'], unique=False)
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_outcome_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=64), nullable=False),
    sa.Column('decimal_odds', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_outcome_id'], ['market_outcomes.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_bookmaker'), 'odds', ['bookmaker'], unique=False)
    op.create_index(op.f('ix_odds_captured_at'), 'odds', ['captured_at'], unique=False)
    op.create_index(op.f('ix_odds_market_outcome_id'), 'odds', ['market_outcome_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_version_id', sa.Integer(), nullable=False),
    sa.Column('market_outcome_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('fair_odds', sa.Float(), nullable=False),
    sa.Column('bookmaker_odds', sa.Float(), nullable=True),
    sa.Column('bookmaker_name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['market_outcome_id'], ['market_outcomes.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_analysis_version_id'), 'predictions', ['analysis_version_id'], unique=False)
    op.create_index(op.f('ix_predictions_market_outcome_id'), 'predictions', ['market_outcome_id'], unique=False)
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('NONE', 'INTERESTING', 'STRONG', name='alertlevel'), nullable=False),
    sa.Column('discrepancy_pct', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_prediction_id'), 'alerts', ['prediction_id'], unique=False)
    op.create_table('risk_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_version_id', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('risk_score_raw', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_version_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_selections_analysis_version_id'), 'risk_selections', ['analysis_version_id'], unique=False)
    op.create_index(op.f('ix_risk_selections_risk_level'), 'risk_selections', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_selections_risk_level'), table_name='risk_selections')
    op.drop_index(op.f('ix_risk_selections_analysis_version_id'), table_name='risk_selections')
    op.drop_table('risk_selections')
    op.drop_index(op.f('ix_alerts_prediction_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_market_outcome_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_analysis_version_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_odds_market_outcome_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_captured_at'), table_name='odds')
    op.drop_index(op.f('ix_odds_bookmaker'), table_name='odds')
    op.drop_table('odds')
    op.drop_index(op.f('ix_market_outcomes_market_id'), table_name='market_outcomes')
    op.drop_table('market_outcomes')
    op.drop_index(op.f('ix_weather_match_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_team_stats_team_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_match_id'), table_name='team_stats')
    op.drop_table('team_stats')
    op.drop_index(op.f('ix_player_stats_team_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_match_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_markets_match_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_category'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_lineups_team_id'), table_name='lineups')
    op.drop_index(op.f('ix_lineups_player_id'), table_name='lineups')
    op.drop_index(op.f('ix_lineups_match_id'), table_name='lineups')
    op.drop_table('lineups')
    op.drop_index(op.f('ix_analysis_versions_match_id'), table_name='analysis_versions')
    op.drop_index(op.f('ix_analysis_versions_is_current'), table_name='analysis_versions')
    op.drop_table('analysis_versions')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_kickoff_utc'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_external_ref'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_backtests_model_version_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_transfers_to_team_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_player_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_tactical_features_team_id'), table_name='tactical_features')
    op.drop_index(op.f('ix_tactical_features_player_id'), table_name='tactical_features')
    op.drop_index(op.f('ix_tactical_features_feature_name'), table_name='tactical_features')
    op.drop_index(op.f('ix_tactical_features_as_of_date'), table_name='tactical_features')
    op.drop_table('tactical_features')
    op.drop_index(op.f('ix_seasons_competition_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_referee_stats_referee_id'), table_name='referee_stats')
    op.drop_index(op.f('ix_referee_stats_as_of_date'), table_name='referee_stats')
    op.drop_table('referee_stats')
    op.drop_index(op.f('ix_model_versions_competition_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_injuries_team_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_player_id'), table_name='injuries')
    op.drop_table('injuries')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_canonical_key'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sources_key'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_referees_name'), table_name='referees')
    op.drop_index(op.f('ix_referees_canonical_key'), table_name='referees')
    op.drop_table('referees')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_canonical_key'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_competitions_code'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_coaches_canonical_key'), table_name='coaches')
    op.drop_table('coaches')
    # ### end Alembic commands ###
